project:
  type: website
  output-dir: ../docs

website:
  title: "EU Omnibus Briefing"
  repo-url: https://github.com/clairembassett/EEUOmnibus.git
  repo-branch: master

  sidebar:
    search: true

  navbar:
    search: true
    left:
      - href: index.qmd
        text: Introduction
      - href: approvedchanges.qmd
        text: Approved Changes
      - text: Proposed Changes
        menu:
          - href: propcsrd.qmd
            text: CSRD
          - href: propcsddd.qmd
            text: CSDDD
          - href: propeutax.qmd
            text: EU Taxonomy
          - href: propcbam.qmd
            text: CBAM
      - text: Client Application
        menu:
          - href: clientaapp.qmd
            text: Client A
          - href: clientbapp.qmd
            text: Client B
      - href: seceffects.qmd
        text: Secondary Effects to ETS
      - href: lawtracker.qmd
        text: EU Law Tracker
      - href: sources.qmd
        text: Bibliography

format:
  html:
    embed-resources: true
    theme:
      - flatly
    css: styles.css
    toc: true